### ISSUE TITLE
ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by kk921710** [lxztju/pytorch_classification#29]
...... Initialize the network done!!! .......
Traceback (most recent call last):
  File "/home/jiannan/project/pytorch_classification-master/train.py", line 76, in <module>
    optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=cfg.LR)
  File "/home/jiannan/anaconda3/envs/pt-gpu/lib/python3.6/site-packages/torch/optim/adam.py", line 42, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/home/jiannan/anaconda3/envs/pt-gpu/lib/python3.6/site-packages/torch/optim/optimizer.py", line 46, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
这个问题要怎么解决？？？

**Comment by WhyFear** [comment]
你好，请问你解决了吗？我是在用densenet的时候出现了和你一样的问题。
